### Get all categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json

### Create new category
POST localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Gaming"
}

### Get category by Id
GET localhost:3000/api/categories/100
X-API-Key: RAHASIA
Accept: application/json

### Update category by id
PUT localhost:3000/api/categories/3
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Shoping"
}

### Delete category by id
DELETE localhost:3000/api/categories/4
X-API-Key: RAHASIA
Accept: application/json